# -*- mode: python -*-
Import("env")

env = env.Clone()

env.Library(
    target='encryption_options',
    source=[
        'encryption_options.cpp',
    ],
    LIBDEPS=[
    ],
)

env.Library(
    target='encryption_vault',
    source=[
    	'encryption_vault.cpp'
    ],
    LIBDEPS=[
    ],
    SYSLIBDEPS=[
        'winhttp' if env.TargetOSIs('windows') else 'curl',
    ],
)
