# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='backup',
    source=[
        'backup_commands.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/storage/storage_options',
    ],
)
