# -*- mode: python; -*-
Import("env")

env.Library(target='tokubackup',
            source=['backup_error.cpp',
                    'backup_status_command.cpp',
                    'start_backup_command.cpp',
                    'throttle_backup_command.cpp',
                    'initiator.cpp'],
            LIBDEPS=[],
            SYSLIBDEPS=['HotBackup']
)
