# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='audit',
    source=[
        'audit_commands.cpp',
        'audit_file.cpp',
        'audit_options.cpp',
        'audit.cpp',
    ],
    LIBDEPS_DEPENDENTS=['$BUILD_DIR/mongo/db/commands'],
)
