# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='audit',
    source=[
        'audit_commands.cpp',
        'audit_file.cpp',
        'audit_options.cpp',
        'audit.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/commands/test_commands_enabled',
        '$BUILD_DIR/mongo/db/matcher/expressions',
        '$BUILD_DIR/mongo/db/pipeline/expression_context',
    ],
    LIBDEPS_DEPENDENTS=[
        '$BUILD_DIR/mongo/db/commands',
    ],
)
